# Copyright 2026 Anubhav Kumar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
######1
SELECT s.std_name
FROM STDUENT s 
WHERE s.DEPT_ID = (SELECT s1.dept_id FROM STDUENT s1 WHERE s1.std_id=23730 );


####2
SELECT s.STD_NAME 
FROM STDUENT s 
WHERE s.STD_GENDER = (SELECT s1.STD_GENDER FROM STDUENT s1 WHERE s1.STD_ID=23729)

###3
SELECT s.std_name
FROM STDUENT s 
WHERE s.DEPT_ID = (SELECT s1.dept_id FROM STDUENT s1 WHERE s1.std_id=23729 );

###4
SELECT S.STD_NAME
FROM STDUENT S 
WHERE EXISTS (SELECT S2.DEPT_ID FROM STDUENT S2 WHERE S2.STD_GENDER ='FEMALE');


SELECT S.STD_NAME 
FROM STDUENT S 
WHERE S.STD_ID IN(SELECT S.STD_ID FROM ENROLLMENT E WHERE E.STD_ID =S.STD_ID);

###6
SELECT S.STD_NAME,S.STD_ID ,E2.COURSE_ID , C.COURSE_NAME
FROM STDUENT S 
INNER JOIN ENROLLMENT E2 
ON E2.STD_ID = S.STD_ID
INNER JOIN COURSE C
ON C.COURSE_ID = E2.COURSE_ID
WHERE EXISTS (SELECT E.ENROLLMENT_ID FROM ENROLLMENT E WHERE E.STD_ID=S.STD_ID);

###7
SELECT C.COURSE_NAME 
FROM COURSE C 
WHERE C.COURSE_CREDITS >= (SELECT AVG(C2.COURSE_CREDITS) AS AVG_CREDITS FROM COURSE C2 );

###8
SELECT S.STD_NAME
 FROM STDUENT S 
 WHERE S.STD_ID > (SELECT AVG(S2.STD_ID)AS AVG_ID FROM STDUENT S2 );


##10
SELECT S.STD_NAME,S.STD_ID 
FROM STDUENT S 
WHERE EXISTS (SELECT E.ENROLLMENT_ID FROM ENROLLMENT E WHERE E.STD_ID=S.STD_ID);

##11
SELECT S.STD_NAME,S.DEPT_ID 
FROM STDUENT S 

###12

SELECT E.COURSE_ID ,COUNT(E.ENROLLMENT_ID) AS TOTAL_STUDENT
FROM ENROLLMENT E 
GROUP BY E.COURSE_ID
HAVING COUNT(E.ENROLLMENT_ID) > 1
;

##13
SELECT C.COURSE_ID 
FROM COURSE C
WHERE C.COURSE_CREDITS = (SELECT MAX(C2.COURSE_CREDITS) FROM COURSE C2);

